### ISSUE TITLE
Contentful CMS

### ISSUE THREAD

**Issue by code-hyper** [SergiusNahnoinyi/job-board-app#31]
Hi Sergius Nahnoinyi,

Nice to meet you.

I like the filtering and search function you built for the job board app! Trying to install on my local machine. 
I'm curious how do you setup your content model in Contentful CMS. I have insert the contenful API. But the job is not appearing. I believe I need to create some field and value in contentful. I would like to learn. Do you mind sharing with me how do you setup contenful?

![Screenshot1](https://user-images.githubusercontent.com/8730264/235053722-6615bcd4-d12d-44b5-87ee-2fc1de42447c.png)

**Comment by SergiusNahnoinyi** [comment]
Here is a tutorial: https://www.youtube.com/watch?v=OfsNhazEReQ&list=PLp8y1n1A-wbh-982nEMPi_RZAWD16Bp4f

**Comment by code-hyper** [comment]
👍Awesome. Thanks for sharing!
